name: Master Github Actions
on:
  workflow_dispatch:
  push:
    branches:
      - 'master' # (main branch) Set branch of the GH repo to push
jobs:
  TelnyxCypress_TestSuite: # Name of the job
      runs-on: ubuntu-20.04 # Choosing OS
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16' # In command line run “node -v” and choose your version
      - run: npm ci
      #  - run: npm config set script-shell "G:\Git\bin\bash.exe"
      - name: run test
        run: npm run testOnHeadlessMode # Our name of the headless script
      
